__title__ = "kiteconnect"
__description__ = "The unofficial Python client for the Kite Connect trading API"
__url__ = "https://kite.trade"
__download_url__ = "https://github.com/nasir101/kiteconnect"
__version__ = "4.1.0"
__author__ = "Kaji Nasiruddin Ahmed"
__author_email__ = "nasir.ciem.it@gmail.com"